export const GET_LOGS = "GET_LOGS";
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_EXPENSES = "GET_EXPENSES";
export const APPROVE_EXPENSE = "APPROVE_EXPENSE";
export const DISAPPROVE_EXPENSE = "DISAPPROVE_EXPENSE";

export const APPROVE_VALUE = 1;
export const DISAPPROVE_VALUE = 2;