"""ApplicationRequestLog table

Revision ID: ded043a4068c
Revises: 
Create Date: 2019-12-27 15:46:52.389855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded043a4068c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_request_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('remote_addr', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('user_agent', sa.String(length=100), nullable=True),
    sa.Column('remote_user', sa.String(length=100), nullable=True),
    sa.Column('application_type', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_request_log_timestamp'), 'application_request_log', ['timestamp'], unique=False)
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_uuid'), 'employee', ['uuid'], unique=True)
    op.create_table('expense',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=4), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('approve_state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_uuid'), 'expense', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_uuid'), table_name='expense')
    op.drop_table('expense')
    op.drop_index(op.f('ix_employee_uuid'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_application_request_log_timestamp'), table_name='application_request_log')
    op.drop_table('application_request_log')
    # ### end Alembic commands ###
